# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'splitbuddy:$(build.buildId)'
  dockerId: 'splitbuddy'
  pswd: rWT6K4+DmhghaSsfdAi0W8dAHPuWViJN

steps:
- script: docker run -v $(Build.SourcesDirectory):/src antonienko/compass-watch:latest compile ./ --output-style compressed --force
  displayName: 'docker run Compass'
- script: chmod -v a+rwx $(Build.SourcesDirectory)/*
  displayName: 'change rights'
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  displayName: 'docker push'
