version: '3'
services:
  webserver:
    image: phpstorm/php-71-apache-xdebug-26
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: 'splitbuddy'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'testpass'
      MYSQL_ROOT_PASSWORD: 'testpass'
    ports:
      - 3306:3306
    expose:
      - 3306
  compass:
    image: antonienko/compass-watch:latest
    command: watch --poll ./
    volumes:
      - ./:/src