version: '3'
services:
  webserver:
    image: mattrayner/lamp:latest
    ports:
      - 80:80
      - 3306:3306
    volumes:
      - ./:/app
    environment:
      MYSQL_ADMIN_PASS: 'asdf'
  compass:
    image: antonienko/compass-watch:latest
    command: watch --poll ./
    volumes:
      - ./:/src